name: Criação de Artifacts
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'lavalink-nodejs.zip'
        exclusions: '*.git* *.eslintrc.json *package-lock.json'
    - name: Automatic Releases
      uses: actions/upload-artifact@v1
      with:
        name: lavalink-nodejs.zip
        path: lavalink-nodejs.zip
